### ISSUE TITLE
多个类包含sql.h时候报错。

### ISSUE THREAD

**Issue by buildwithyang** [six-ddc/sql-builder#2]
class A class B 同时使用的时候。貌似是多次实例化了。
报错
duplicate symbol __ZTVN3sql11UpdateModelE in:
    CMakeFiles/server.dir/src/Dao/GWDao/GWDaoImpl.cpp.o
    CMakeFiles/server.dir/src/Dao/DCDao/DiCiDaoImpl.cpp.o

**Comment by six-ddc** [comment]
已修复
