### ISSUE TITLE
Join support

### ISSUE THREAD

**Issue by JackLilhammers** [six-ddc/sql-builder#6]
Do you have any plans to support joins?
I've looked into the fork from Yang Zzhong, who made the pull request, but it's not compatible with your repo...

**Comment by six-ddc** [comment]
It's supported now.

**Comment by JackLilhammers** [comment]
Cool!
I'll test it right now. I've added a simple std::string container to insert named parameters for prepared queries.
I've added a couple of lines to handle the creation of prepared queries. Can I issue a PR?

**Comment by six-ddc** [comment]
Sure you can.
